### PR TITLE
Added extra bounding box function to return tsv-like info

### PR DESCRIPTION
**Pull request by shogg-isentia**
The original tesseract cli can return tabular output with the `tsv` flag. This is particularly useful for the fact that it gives you the full structure of relationships between words, lines, paragraphs and blocks. The original code in question is here: https://github.com/tesseract-ocr/tesseract/blob/01535706ecd11a495f9f6e65ee0118b3537a115a/src/api/baseapi.cpp#L1338

This pull request replicates that functionality for gosseract.

### CODE REVIEW

**Comment by otiai10** [comment]
Thank you,

just for myself, let me update develop branch so that the diff is more specific. 🙏

**Comment by shogg-isentia** [comment]
Hi again, 

An additional commit has been included to expose the list of available languages in Tesseract.

**Comment by shogg-isentia** [comment]
Apologies for pushing a commit that broke the CI process, that should be fixed now.

**Comment by otiai10** [comment]
Thank you for sending pull-request.
Your PR seems including changes which are not directly related to what you want to add. If it's right, could you please separate your pull-request to make it clear.

**Comment by shogg-isentia** [comment]
Apologies, we'll do that shortly

**Comment by shogg-isentia** [comment]
Closing this request, will create a new one for each of the changes

**Pull request closed without merging**
