### PR TITLE
Add mutex to handle concurrency

### PR DESCRIPTION
**Pull request by muharihar**
Add mutex to handle concurrency

### CODE REVIEW

**Comment by otiai10** [comment]
Overall, as I understand, you want to reuse and share 1 client from multiple concurrency, is it right?
Why not create and close 1 client for 1 program unit (may be goroutine)?

**Comment by otiai10** [comment]
Regarding the patch, the mutex of a client does not get unlocked if any errors. That's because the tests failed.

In the idea of you, because the client is supposed be shared by other goroutines, the client should be unlocked if it results in any error.

Thank you very much for your suggestion after all.

**Comment by muharihar** [comment]
Will check it in my case, Thanks for you suggestion @otiai10.

**Comment by otiai10** [comment]
@muharihar, can I close this PR for now?

**Comment by muharihar** [comment]
> @muharihar, can I close this PR for now?

yes, sure...

**Comment by otiai10** [comment]
Thank you for your contribution, anyway

**Pull request closed without merging**
