### PR TITLE
Change wording (outside of tesseract references)

### PR DESCRIPTION
**Pull request by jabberwock**
Let's get better with our use of words.

- https://www.ncsc.gov.uk/blog-post/terminology-its-not-black-and-white
- https://www.vice.com/en/article/v7dd3d/we-need-to-stop-saying-blacklist-and-whitelist
- https://insights.dice.com/2020/07/17/whitelist-blacklist-the-new-debate-over-security-terminology/

### CODE REVIEW

**Comment by jabberwock** [comment]
Thank you for addressing this!

**Comment by otiai10** [comment]
@jabberwock can you please rebase this pull request or anything to resolve the conflict?

**Review by otiai10 — CHANGES_REQUESTED** [review]
Keep `SetWhitellist` and `SetBlacklist` with marking `// TODO: Delete`.
And call new `SetAllowlist` and `SetBlocklist` internally from old funcs.
This is for backward compatible.

**Comment by jabberwock** [comment]
The whole purpose was to change the wording. Not to leave it in. I won't be making any more changes. Take care.

**Pull request closed without merging**
