### PR TITLE
Ability to direct output to a file or disable it.

### PR DESCRIPTION
**Pull request by emil2k**
By setting `debug_file`.

### CODE REVIEW

**Comment by otiai10** [comment]
LGTM. Thank you!

**Comment by otiai10** [comment]
Could you please write tests for this feature? or I will

**Comment by emil2k** [comment]
I will try. Will send you a PR with a test next week.

**Comment by emil2k** [comment]
I looked into trying to make a unit test for this but found no good way to do it.

What I would essentially want to test is if `tprintf` is properly redirecting its output to a file instead of `stderr`, but I'm not sure how to invoke `tprintf` directly and using some indirect way like calling some method on the base API with particular parameters to make it invoke `tprintf` seems too hackish of a solution.

Do you have any suggestions?

**Pull request merged**
