### PR TITLE
add GetAvailableLanguages

### PR DESCRIPTION
**Pull request by xiahongze**
@otiai10 we could list available languages from the default location.

### CODE REVIEW

**Comment by xiahongze** [comment]
Related to [PR#166](https://github.com/otiai10/gosseract/pull/166)

**Comment by otiai10** [comment]
Is it difficult to add test cases for this method?

**Comment by xiahongze** [comment]
@otiai10 I added a test for this PR. Not sure if it works as intended because I am not sure about your docker env, aka, what languages do you install in the machine. For now, I assumed you installed `eng` and `osd` as provided by tesseract.

**Comment by otiai10** [comment]
Thank you!

**Pull request merged**
