### PR TITLE
Added extra bounding box function to return more detail in line with …

### PR DESCRIPTION
**Pull request by xiahongze**
@otiai10 here is one commit we made to add more verbosity to the bounding boxes. Thanks

### CODE REVIEW

**Comment by otiai10** [comment]
@xiahongze Thank you

**Comment by xiahongze** [comment]
Related to [PR166](https://github.com/otiai10/gosseract/pull/166)

**Comment by otiai10** [comment]
I can see many formatting change in your pull-request. Could you specify which formatter you are using? The main change seems nice.

**Comment by xiahongze** [comment]
@otiai10 Ochiai San, I used clang-formatter with the setting below:

`{ BasedOnStyle: Google, IndentWidth: 4, IndentCaseLabels: true, NamespaceIndentation: All , ColumnLimit: 120}`

Please modify the code at your will.

**Pull request merged**
